import os
from building import *
import BuildLists as bl

cwd = GetCurrentDir()
objs = []
# list = os.listdir(cwd)

for d in bl.LIBS:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
    else:
        print('Error: can not find SConscript in ' + path)
        exit(0)

Return('objs')
