from building import *

cwd     = GetCurrentDir()

src     = Glob('*.c')
src    += Glob('testcase/*.c')

CPPPATH = [cwd]

group   = DefineGroup('utest', src, depend = ['FMT_USING_UNIT_TEST'], CPPPATH = CPPPATH)

Return('group')
