from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
src += Glob('vehicle/multicopter/*.c') # todo, add sconscript for each vehicle type
src += Glob('comm/*.c')
src += Glob('logger/*.c')
src += Glob('fmtio/*.c')
src += Glob('status/*.c')

CPPPATH = [cwd]

group = DefineGroup('Task', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

