from building import *
import build_obj

cwd = GetCurrentDir()

src = []
for f in build_obj.TASKS:
    src += Glob(f)

inc = []
for d in build_obj.TASKS_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('Task', src, depend = [''], CPPPATH = inc)

Return('group')

