from building import *
import build_obj

cwd = GetCurrentDir()

src = []
for f in build_obj.HAL:
    src += Glob(f)

inc = []
for d in build_obj.HAL_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('HAL', src, depend = [''], CPPPATH = inc)

Return('group')
