from building import *
import buildlist as bl

cwd = GetCurrentDir()

src = []
for f in bl.MODELS:
    src += Glob(f)

inc = []
for d in bl.MODELS_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('Model', src, depend=[''], CPPPATH=inc)

if GetOption('PX4_ECL'):
    src = []
    for f in bl.MODELS_PX4_ECL:
        src += Glob(f)
    inc = []
    for d in bl.MODELS_CPPPATH_PX4_ECL:
        inc += [cwd + '/' + d]
    group = group + DefineGroup('Model_PX4_ECL', src, depend=[''], CPPPATH=inc, 
                                CPPDEFINES=['ECL_STANDALONE'],CXXFLAGS=['-Wno-overloaded-virtual'])

Return('group')
