Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()

src = Glob('libcanard/*.c')
src += Glob('dsdlc_generated/src/*.c')

CPPPATH = [cwd + '/libcanard', cwd + '/dsdlc_generated/include']


group = DefineGroup('dronecan', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
