Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('cm_backtrace', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
