# for module compiling
Import('rtconfig')
import os
from building import *
		
if rtconfig.BOARD == 'pixhawk':
	objs = SConscript('stm32f4/SConscript')
elif rtconfig.BOARD == 'pixhawk4':
	objs = SConscript('stm32f7/SConscript')
else:
	objs = []

Return('objs')
