# for module compiling
Import('rtconfig')
import os
from building import *
		
if rtconfig.CPU == 'cortex-m4':
	objs = SConscript('stm32f4/SConscript')
elif rtconfig.CPU == 'cortex-m7':
	objs = SConscript('stm32f7/SConscript')
else:
	objs = []

Return('objs')
