from building import *

cwd = GetCurrentDir()
src	= []
inc = []

src += Glob('*.c')
src += Glob('lib/*.c')

inc += [cwd]
inc += [cwd + '/lib']

group = DefineGroup('Base_INS', src, depend = [''], CPPPATH = inc)

Return('group')
