# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

src	= Glob('source/*.c')
CPPPATH = [cwd, cwd + '/source']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

