import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Glob('CMSIS/Device/ST/STM32F7xx/Source/Templates/system_stm32f7xx.c')
src += Glob('STM32F7xx_HAL_Driver/Src/*.c')

#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f765xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['CMSIS/Device/ST/STM32F7xx/Source/Templates/arm/startup_stm32f765xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['CMSIS/Device/ST/STM32F7xx/Source/Templates/iar/startup_stm32f765xx.s']

#add for DSP library
src += Glob('CMSIS/DSP/Source/FastMathFunctions/*f32.c')
src += Glob('CMSIS/DSP/Source/BasicMathFunctions/*f32.c')
src += Glob('CMSIS/DSP/Source/MatrixFunctions/*f32.c')
src += Glob('CMSIS/DSP/Source/SupportFunctions/*f32.c')

path = [cwd + '/STM32F7xx_HAL_Driver/Inc', 
    cwd + '/CMSIS/Device/ST/STM32F7xx/Include',
    cwd + '/CMSIS/DSP/Include',
	cwd + '/CMSIS/Include']

#CPPDEFINES = ['USE_STDPERIPH_DRIVER', 'ARM_MATH_CM4', 'ARM_MATH_MATRIX_CHECK']
#defines = ['USE_STDPERIPH_DRIVER', 'ARM_MATH_CM4', 'ARM_MATH_MATRIX_CHECK']
group = DefineGroup('STM32_StdPeriph', src, depend = [''], CPPPATH = path)

Return('group')
