Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('src/c/core/log/*.c')
src += Glob('src/c/core/serialization/*.c')
src += Glob('src/c/core/session/*.c')
src += Glob('src/c/core/session/stream/*.c')
src += Glob('src/c/profile/transport/serial/serial_transport_external.c')
src += Glob('src/c/profile/transport/serial/serial_transport.c')
src += Glob('src/c/profile/transport/serial/serial_protocol.c')
src += Glob('src/c/util/*.c')
src += Glob('ucdr/src/c/*.c')
src += Glob('ucdr/src/c/types/*.c')
# Example Source
src += Glob('examples/PingPong/Header.c')
src += Glob('examples/PingPong/Time.c')
src += Glob('examples/PingPong/pingpong_main.c')

inc = [cwd + '/src/c/core/log',
	cwd + '/src/c/core/serialization',
	cwd + '/src/c/core/session',
	cwd + '/src/c/core/session/stream',
	cwd + '/src/c/profile/transport/serial',
	cwd + '/src/c/util',
	cwd + '/include',
	cwd + '/ucdr/src/c',
	cwd + '/ucdr/include',
	cwd + '/examples/PingPong']


group = DefineGroup('Micro-XRCE-DDS-Client', src, depend = [''], CPPPATH = inc)

Return('group')
