from building import *
import BuildLists as bl

cwd = GetCurrentDir()

src = []
for f in bl.HAL:
    src += Glob(f)

inc = []
for d in bl.HAL_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('HAL', src, depend = [''], CPPPATH = inc)

Return('group')
