import os
from building import *
import build_obj

cwd = GetCurrentDir()
objs = []
# list = os.listdir(cwd)

for d in build_obj.LIBS:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
    else:
        print 'Error: can not find SConscript in ' + path
        exit(0)

Return('objs')
