from building import *
import build_obj

cwd = GetCurrentDir()

src = []
for f in build_obj.MODULES:
    src += Glob(f)

inc = []
for d in build_obj.MODULES_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('Module', src, depend=[''], CPPPATH=inc)

Return('group')
