from building import *
import build_obj

cwd = GetCurrentDir()

src = []
for f in build_obj.DRIVERS:
    src += Glob(f)

inc = []
for d in build_obj.DRIVERS_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('Driver', src, depend = [''], CPPPATH = inc)

Return('group')

