import os
from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd, cwd + '/src']

group = DefineGroup('Firmament', src, depend = [''], CPPPATH = CPPPATH)

list = filter(os.path.isdir, os.listdir(cwd))

list = os.listdir(cwd)
list.remove('SConscript')
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')