import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
#src = Glob('CMSIS/Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c')
src = []
src += Glob('STM32F4xx_StdPeriph_Driver/src/*.c')

#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['CMSIS/Device/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f427x.s']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['CMSIS/Device/ST/STM32F4xx/Source/Templates/arm/startup_stm32f427x.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['CMSIS/Device/ST/STM32F4xx/Source/Templates/iar/startup_stm32f427x.s']

#add for DSP library
src += Glob('CMSIS/DSP_Lib/Source/FastMathFunctions/*f32.c')
src += Glob('CMSIS/DSP_Lib/Source/BasicMathFunctions/*f32.c')
src += Glob('CMSIS/DSP_Lib/Source/MatrixFunctions/*f32.c')
src += Glob('CMSIS/DSP_Lib/Source/SupportFunctions/*f32.c')

path = [cwd + '/STM32F4xx_StdPeriph_Driver/inc', 
    cwd + '/CMSIS/Device/ST/STM32F4xx/Include',
    cwd + '/CMSIS/Include']

#CPPDEFINES = ['USE_STDPERIPH_DRIVER', rtconfig.STM32_TYPE]
CPPDEFINES = ['USE_STDPERIPH_DRIVER', 'ARM_MATH_CM4', 'ARM_MATH_MATRIX_CHECK']
group = DefineGroup('STM32_StdPeriph', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
