from building import *
import BuildLists as bl

cwd = GetCurrentDir()

src = []
for f in bl.MODULES:
    src += Glob(f)

inc = []
for d in bl.MODULES_CPPPATH:
    inc += [cwd + '/' + d]

group = DefineGroup('Module', src, depend=[''], CPPPATH=inc)

Return('group')
